development:
  adapter: postgresql
  encoding: unicode
  database: salty_development
  pool: 5
  username: salty
  password: salty
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: salty_test
  pool: 5
  username: salty
  password: salty
  host: localhost
  port: 5432
